import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="bg-no-repeat bg-cover bg-left" style={{ backgroundImage: "url('dam-vault-background.jpg')" }}>{children}</div>;
}
